### ISSUE TITLE
Mint/Mojito possibly leaking {:tcp_closed, port}

### ISSUE THREAD

**Issue by dowusu** [elixir-mint/mint#231] opened 2019-12-30 21:29 UTC
I ran into a strange error today whiles working with Mojito. I've a GenServer that invokes an http endpoint via Mojito. Initially it was crashing with undefined function clause for handle_info, after adding a general function clause, {:tcp_closed, port} was being sent to the GenServer. It's quite surprising since I've Mojito in production with no such message. I've hackney in my codebase as well but the GenServer generating this message uses only Mojito. Could it be that Mojito/Mint is sending the above message to the GenServer.

**Comment by ericmj** [comment] 2019-12-30 23:29
Mint cannot leak messages by definition since it requires the user to pass all messages to mint. To help you look into the issue in more detail we need more information if you have a way to reproduce the issue, preferably without mojito, it would help us help you.

For now I will close the issue because it is not actionable by us. If you can provide more information we will reopen the issue.

**Closed by ericmj** 2019-12-30 23:29 UTC
