### ISSUE TITLE
Errors in EOF processing in v1.2

### ISSUE THREAD

**Issue by bpardee** [elixir-mint/mint#291] opened 2021-01-10 18:24 UTC
I upgraded from v1.1 to v1.2 and started getting an error that wasn't occurring before.  It appears to be some subtle timing issue when it reads the last chunk of data.  I can reproduce with the following code on a 3M S3 file:

```elixir
defmodule S3 do
  defstruct [:conn, done: false]

  @sleep 500

  def run(bucket, path) do
    presigned_url(bucket, path)
    |> get_stream()
    |> Enum.each(fn body ->
      nil
    end)
  end

  def presigned_url(bucket, path) do
    {:ok, url} =
      ExAws.Config.new(:s3)
      |> ExAws.S3.presigned_url(:get, bucket, path)

    url
  end

  def get_stream(url) do
    Stream.resource(
      fn -> open_url(url) end,
      &receive_responses/1,
      &close/1
    )
  end

  defp open_url(url) do
    uri = URI.parse(url)
    {:ok, conn} = Mint.HTTP.connect(String.to_atom(uri.scheme), uri.host, uri.port)

    {:ok, conn, _request_ref} =
      Mint.HTTP.request(conn, "GET", uri.path <> "?" <> uri.query, [], nil)

    %__MODULE__{conn: conn}
  end

  defp close(%{conn: conn}) do
    Mint.HTTP.close(conn)
  end

  defp receive_responses(state = %{done: true}) do
    IO.inspect(state, label: :done)
    {:halt, state}
  end

  defp receive_responses(state) do
    IO.inspect(state, label: :msg_loop)

    receive do
      message ->
        case Mint.HTTP.stream(state.conn, message) do
          :unknown ->
            IO.puts("Received unknown: #{inspect(message)}")
            receive_responses(state)

          {:ok, conn, responses} ->
            state = %__MODULE__{conn: conn}

            Enum.reduce(responses, state, &process_response/2)
            |> receive_responses()
        end
    after
      5_000 -> raise "receive timeout"
    end
  end

  defp process_response({:status, _request_ref, status}, state) do
    IO.puts("response_status=#{status}")
    state
  end

  defp process_response({:headers, _request_ref, headers}, state) do
    IO.inspect(headers, label: :response_headers)
    state
  end

  defp process_response(response = {:data, _request_ref, new_data}, state) do
    IO.inspect(response, label: :response_data)
    :timer.sleep(@sleep)
    state
  end

  defp process_response(response = {:done, _request_ref}, state) do
    IO.inspect(response, label: :response_done)
    Map.put(state, :done, true)
  end
end
```

Here is the last part of the output I get:
```
msg_loop: %S3{
  conn: %Mint.HTTP1{
    buffer: "",
    host: "s3.amazonaws.com",
    mode: :active,
    port: 443,
    private: %{},
    request: %{
      body: {:content_length, 60922},
      connection: [],
      content_length: 530375,
      data_buffer: [],
      headers_buffer: [],
      method: "GET",
      ref: #Reference<0.1584105302.338427910.243527>,
      state: :body,
      status: 200,
      transfer_encoding: [],
      version: {1, 1}
    },
    requests: {[], []},
    scheme_as_string: "https",
    socket: {:sslsocket, {:gen_tcp, #Port<0.162>, :tls_connection, :undefined},
     [#PID<0.18603.0>, #PID<0.18602.0>]},
    state: :open,
    transport: Mint.Core.Transport.SSL
  },
  done: false
}
response_data: {:data, #Reference<0.1584105302.338427910.243527>,
 "bunch of data here" <> ...}
msg_loop: %S3{
  conn: %Mint.HTTP1{
    buffer: "",
    host: "s3.amazonaws.com",
    mode: :active,
    port: 443,
    private: %{},
    request: %{
      body: {:content_length, 43514},
      connection: [],
      content_length: 530375,
      data_buffer: [],
      headers_buffer: [],
      method: "GET",
      ref: #Reference<0.1584105302.338427910.243527>,
      state: :body,
      status: 200,
      transfer_encoding: [],
      version: {1, 1}
    },
    requests: {[], []},
    scheme_as_string: "https",
    socket: {:sslsocket, {:gen_tcp, #Port<0.162>, :tls_connection, :undefined},
     [#PID<0.18603.0>, #PID<0.18602.0>]},
    state: :open,
    transport: Mint.Core.Transport.SSL
  },
  done: false
}
** (CaseClauseError) no case clause matching: {:error, %Mint.HTTP1{buffer: "", host: "s3.amazonaws.com", mode: :active, port: 443, private: %{}, request: nil, requests: {[], []}, scheme_as_string: "https", socket: {:sslsocket, {:gen_tcp, #Port<0.162>, :tls_connection, :undefined}, [#PID<0.18603.0>, #PID<0.18602.0>]}, state: :closed, transport: Mint.Core.Transpo\
rt.SSL}, %Mint.TransportError{reason: :closed}, [{:data, #Reference<0.1584105302.338427910.243527>, "bunch of data here" <> ...}, {:done, #Reference<0.1584105302.338427910.243527>}]}
    iex:188: S3.receive_responses/1
    (elixir 1.11.2) lib/stream.ex:1421: Stream.do_resource/5
    (elixir 1.11.2) lib/enum.ex:3461: Enum.each/2
```

If i change the code so @sleep is only 100, it works fine and I get the following output:
```
msg_loop: %S3{
  conn: %Mint.HTTP1{
    buffer: "",
    host: "s3.amazonaws.com",
    mode: :active,
    port: 443,
    private: %{},
    request: %{
      body: {:content_length, 8698},
      connection: [],
      content_length: 530375,
      data_buffer: [],
      headers_buffer: [],
      method: "GET",
      ref: #Reference<0.1584105302.338427912.231572>,
      state: :body,
      status: 200,
      transfer_encoding: [],
      version: {1, 1}
    },
    requests: {[], []},
    scheme_as_string: "https",
    socket: {:sslsocket, {:gen_tcp, #Port<0.161>, :tls_connection, :undefined},
     [#PID<0.18497.0>, #PID<0.18496.0>]},
    state: :open,
    transport: Mint.Core.Transport.SSL
  },
  done: false
}
response_data: {:data, #Reference<0.1584105302.338427912.231572>,
 "bunch of data here" <> ...}
response_done: {:done, #Reference<0.1584105302.338427912.231572>}
done: %S3{
  conn: %Mint.HTTP1{
    buffer: "",
    host: "s3.amazonaws.com",
    mode: :active,
    port: 443,
    private: %{},
    request: nil,
    requests: {[], []},
    scheme_as_string: "https",
    socket: {:sslsocket, {:gen_tcp, #Port<0.161>, :tls_connection, :undefined},
     [#PID<0.18497.0>, #PID<0.18496.0>]},
    state: :open,
    transport: Mint.Core.Transport.SSL
  },
  done: true
}
:ok
```

It also works if I patch in the 1.1 version of Mint.HTTP1.  1.2 and master both fail

**Comment by ericmj** [comment] 2021-01-10 21:04
Can you make an S3 object that causes the error public so that we can reproduce the issue?

**Comment by ericmj** [comment] 2021-01-10 21:09
Actually, there is no issue here. You are not handling that S3 closed the connection after you received the full response. Mint returns the following:

```
{:error, %Mint.HTTP1{buffer: "", host: "s3.amazonaws.com", mode: :active, port: 443, private: %{}, request: nil, requests: {[], []}, scheme_as_string: "https", socket: {:sslsocket, {:gen_tcp, #Port<0.162>, :tls_connection, :undefined}, [#PID<0.18603.0>, #PID<0.18602.0>]}, state: :closed, transport: Mint.Core.Transpo\
rt.SSL}, %Mint.TransportError{reason: :closed}, [{:data, #Reference<0.1584105302.338427910.243527>, "bunch of data here" <> ...}, {:done, #Reference<0.1584105302.338427910.243527>}]}
```

The last element of the tuple is: `[{:data, #Reference<0.1584105302.338427910.243527>, "bunch of data here" <> ...}, {:done, #Reference<0.1584105302.338427910.243527>}]`. This is the last data of the response including `:done` that signals that you received the full response.

So you did receive the full S3 object in the response it just happens that S3 is also closing the connection after you received the response so you need to open a new connection if you are going to make subsequent requests.

**Closed by ericmj** 2021-01-10 21:09 UTC

**Comment by bpardee** [comment] 2021-01-10 23:01
So you're saying that I should be reading the responses from the :error tuple similar to the :ok tuple and since it contains a :done response I can infer that it isn't actually an error?

**Comment by ericmj** [comment] 2021-01-11 01:04
> So you're saying that I should be reading the responses from the :error tuple similar to the :ok tuple and since it contains a :done response I can infer that it isn't actually an error?

Yes. It is an error in the sense that the connection was closed, but that does not mean the request/response was not successful.

Mint follows the Erlang/Elixir the convention to signal a connection closing through an error message, but connections closing are a natural occurrence in networked applications and may not be an actual error condition in your application. Since data may have arrived (in your case the final data of the response) before the connection closed we return this data with the error tuple.
